### ISSUE TITLE
Google SERP items number

### ISSUE THREAD

**Issue by nlemoine** [eyecatchup/SEOstats#102]
`getSerps` always return only 10 results, whatever the number of results you specified as second parameter.

**Comment by nlemoine** [comment]
Sorry, just saw that the PR #101 was adressing this issue. The fix works great. 

But the position is not fully reliable compared to a regular user search. The parameter `filter` is not added in the default query string.

**Comment by jamesspittal** [comment]
> Sorry, just saw that the PR #101 was resolving this issue. The fix works great.

That pull request has now been merged in to the `master` branch.

> But the position returned is not fully reliable compared to a regular user search. The parameter filter is not added in the default query string. I noticed a difference between results with and without this parameter.

Just noticed something similar myself.
