### ISSUE TITLE
Failed to generate a valid hash for PR check.

### ISSUE THREAD

**Issue by PGDesolator** [eyecatchup/SEOstats#118]
I'm facing a rather interesting problem. The google page rank runs fine in the example and returns an actual page rank but when I used the same code on my project it returns the "Failed to generate a valid hash for PR check." message. The google speed score is running without any issues.

I'm running this project on Windows 7 64bit using NetBeans IDE

**Comment by PGDesolator** [comment]
Ok it happens to google speed score sometimes as well. However, its all random as I get scores for some of the Web pages while others return the PR check error.

**Comment by fnagel** [comment]
Same issue here. Tested a few hundred different domains and about 60% fails with the above error message. I tried to debug this but without success. Seems not related to specific domains (as one works and works not, apparently without any specific reason). 

Tested on two different servers (debian squeeze).

**Comment by arfen84** [comment]
Hello
I have the same problem. First it worked fine with all domains, now It doesn't work with domain that it worked before. 
Does I check too much sites in too short time?
I send greatings.

**Comment by ctepeo** [comment]
Just want to confirm that the problem still exists. It also returns wrong result for Google::getBacklinksTotal() function, I checked same domain via simple GuzzleHTTP request (google.com/search?q=site:mydomain.com), parsed response and got the right result.

**Comment by eyecatchup** [comment]
Pagerank is obsolete since Google officially killed it and will be removed. As for @ctepeo's comment.. Please open a separated issue. Your issue is not related to Pagerank.

**Comment by eyecatchup** [comment]
Closed in favor of #135
