### ISSUE TITLE
Twitter Share API does not work

### ISSUE THREAD

**Issue by hughsaffar** [eyecatchup/SEOstats#119]
It seems Social::getTwitterShares does not work! It returns N.A. Might be the end point changed.

**Comment by voku** [comment]
"Update Nov. 20, 2015: As described above, we have now shipped the updated Tweet Button and removed the Tweet count endpoint." - https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

**Comment by eyecatchup** [comment]
Closed in favor of #137
