### ISSUE TITLE
How do I use proxy with SEOstats?

### ISSUE THREAD

**Issue by prionkor** [eyecatchup/SEOstats#123]
I didn't find any documentation on some basic stuff that I need to setup when using SEOstats on live server.

For example: 

1. How do I set proxy server IP on SEO stat? 
2. How to change user-agent when SEO stat makes request. 

[Looking at the source code](https://github.com/eyecatchup/SEOstats/blob/master/SEOstats/Helper/HttpRequest.php). It seem all those parameters are hard coded. What is the workaround?

**Comment by dadopl** [comment]
I join to the question

**Comment by prionkor** [comment]
Not sure why I didn't get email notification! sigh!

**Comment by eyecatchup** [comment]
Closed by merging @tholu's PR (#129)
