### ISSUE TITLE
Google PR returns 0 for all urls

### ISSUE THREAD

**Issue by ordin2342** [eyecatchup/SEOstats#130]
Strangly it worked once, returning 10 for www.google.com. 

But after that every url returns 0, although the real value is different. Does google block more than a single request per IP maybe? No clue, what's wrong.

Alexa stats look correct. Any advice?

Thanks and awesome library by the way!

**Comment by ordin2342** [comment]
Well I was wrong, even the initial request returned actually "1" "0"
Alexa = 1
GooglePR = 0

I just read it wrong as "10"

**Comment by bandertron** [comment]
Hi there, Google confirmed they had stopped returning toolbar PR the other week. As a result there is no way to get this information any more. It's actually been old/non updated data for years now so a good thing that they turned it off in a way.

You can read more here: http://searchengineland.com/google-has-confirmed-they-are-removing-toolbar-pagerank-244230

Hope that helps.

**Comment by ordin2342** [comment]
Thanks mate, I didn't know. Bummer. Is there a different but similar value? I find Alexa is a little hard to grasp from a users point of view. For most people's web sites the Alexa number is also pretty disappointing.
I'm looking for a simple value representing the url in terms of ranking for inexperienced users.

**Comment by bandertron** [comment]
No problem! There are alternatives that you may want to consider provided by Moz, aHref, majestic etc. These generally provide domain rank, page rank as well as trust flow. Worth checking out. Note, all these metrics represent the link profile the website/page has from the web as a whole (well, the depth of their individual Web indexes), which is similar to pagerank.

**Comment by ordin2342** [comment]
All right, gonna check it out. Thanks again! 

My question has been answered, closing this thread.
