### ISSUE TITLE
Config in interface constants

### ISSUE THREAD

**Issue by JacobDorman** [eyecatchup/SEOstats#98]
Is SEOStats configured by directly editing interface constants inside the vendor directory?
eg, `vendor/seostats/seostats/SEOstats/Config/ApiKeys.php` for mozscape API keys

Maybe something like https://github.com/vlucas/phpdotenv would be a better approach.

**Comment by jrobles-boom** [comment]
+1

**Comment by hughsaffar** [comment]
+1

**Comment by xarvel** [comment]
+1

**Comment by mhammerschmidt** [comment]
Is there currently any workaround to set the API keys in case the vendor directory is not checked-in?

**Comment by mhammerschmidt** [comment]
We try to make a PR

**Comment by Gemorroj** [comment]
any news?

**Comment by eyecatchup** [comment]
Closed by merging @mhammerschmidt's PR (#131)
